### ISSUE TITLE
"Request" session-support

### ISSUE THREAD

**Issue by lessp** [BuckleTypes/bs-express#54]
Hi!

Many thanks for creating these bindings, I'm currently working on a project where I needed bindings for [cookie-session](https://github.com/expressjs/cookie-session).

Right now I've built and linked this package locally where I just naively added 
```ocaml
let session: t => option(Js.Dict.t(Js.Json.t));
```

and 

```ocaml
[@bs.get] [@bs.return null_undefined_to_opt]
external session : t => option(Js.Dict.t(Js.Json.t)) = "";
```

and put them below `signedCookies` in `Express.re` and `Express.rei` respectively which seems to work. 

My bindings for `cooke-session` is currently very barebones, but could probably publish when I've added more as I go along.

Anyway, would you like me to create a PR to add this, or do you have other ideas?

Thanks,
Tom

**Comment by ncthbrt** [comment]
Hi @lessp. Thanks for this. 

I'm a little skeptical about this change, mostly because it session seems to be something which requires an additional middleware to be installed. I know there is precedent with the body field and body-parser, but I still feel kind of uncomfortable about further flipping the dependency hierarchy like this.

Would it not be possible for your session library to take in the request object instead and possibly provide a nicer API to manipulate the session?

**Comment by lessp** [comment]
Hey @ncthbrt!

Absolutely! It did cross my mind to extend the API for my bindings, but I thought perhaps it’d be more familiar to extend the Request. 

Anyway, I’ll do that, thanks! 🙂
