### ISSUE TITLE
replace sendFile and json bindings with Js.Json.t

### ISSUE THREAD

**Issue by bassjacob** [BuckleTypes/bs-express#6]
See https://github.com/BuckleTypes/Rexpress/pull/5 for context. Replace loose bindings of 'a with Js.Json.t where appropriate.

**Comment by chenglou** [comment]
Let's wait a bit and test the new JSON serialization/deserialization. The current usage of GADT is a bit inconvenient and for deserialization, you'd have to know the internal representation of bs data structures (very unsafe). Unless during serialization you translate your data structures into vanilla JS data structures and do the opposite for deserialization.

See https://github.com/bloomberg/bucklescript/pull/1382 and the other PRs by @mransan

**Comment by mransan** [comment]
@chenglou @bassjacob I am pretty much typing the entire Express API because I realize you need to look at everything to understand how everything work. I have lots of PR coming end of this week!

Regarding Js_json I agree it should be used in quite a few places instead of 'a. This will part of my change.

**Comment by mransan** [comment]
@chenglou @bassjacob  https://github.com/mransan/bs-express/blob/master/src/express.ml is the WIP

**Comment by mransan** [comment]
First changes at #8

**Comment by bassjacob** [comment]
closing this for now. thanks @mransan for the #8 typing :smile:
